deployments:
  - name: deployment1
    replicas: 3
    image: my-image:latest
    volumeMounts:
      - name: volume1
        mountPath: /path/to/mount1
      - name: volume2
        mountPath: /path/to/mount2
    env:
      - name: ENV_VAR1
        value: value1
      - name: ENV_VAR2
        value: value2
    volumes:
      - name: volume1
        secret:
          secretName: secret1
          defaultMode: 0400
      - name: volume2
        configMap:
          name: configmap1
      - name: volume3
        persistentVolumeClaim:
          claimName: lab-cluster-provisioner-pvc
    livenessProbe:
      initialDelaySeconds: 15
      periodSeconds: 20
      failureThreshold: 3
      successThreshold: 1
      timeoutSeconds: 10
      httpGet:
        path: /health
        port: 8081
    # startupProbe:
    #   initialDelaySeconds: 30
    #   periodSeconds: 10
    #   timeoutSeconds: 5
    #   failureThreshold: 5
    #   successThreshold: 1
    #   httpGet:
    #     path: /health
    #     port: 8081
    # readinessProbe:
    #   initialDelaySeconds: 10
    #   periodSeconds: 15
    #   timeoutSeconds: 5
    #   failureThreshold: 3
    #   successThreshold: 1
    #   httpGet:
    #     path: /health
    #     port: 8081
    resources:
      limits:
        cpu: "2"
        memory: "2Gi"
      requests:
        cpu: "1"
        memory: "512Mi"

hpa:
  - name: deployment1-hpa
    targetDeployment: deployment1
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80

services:
  - name: service1
    deployment: deployment1
    port: 8080
  - name: service2
    deployment: deployment2
    port: 8081

ingress:
  enabled: true
  name: devx-helm
  ingressClassName: nginx
  hosts:
    - example.com
    - example2.com
  paths:
    - path: /service1
      pathType: Prefix
      service: service1
      port: 8080
    - path: /service2
      pathType: ImplementationSpecific
      service: service2
      port: 8081
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  tls:
    enabled: true
    secretName: tls-secret

configmaps:
  - name: configmap1
    data:
      key1: value1
  - name: configmap2
    data:
      key2: value2
