{{- range .Values.services }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  selector:
    app: {{ .deployment }}
  ports:
    - protocol: TCP
      port: {{ .port }}
      targetPort: {{ .port }}
{{- end }}
